import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const handleTokenizeCard = () => {
		axios.post(
			'https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi',
			{
				language: 'es',
				command: 'CREATE_TOKEN',
				merchant: {
					apiLogin: 'pRRXKOl8ikMmt9u',
					apiKey: '4Vj8eK4rloUd272L48hsrarnUA',
				},
				creditCardToken: {
					payerId: '10',
					name: 'APPROVED',
					identificationNumber: '32144457',
					paymentMethod: 'VISA',
					number: '4037997623271984',
					expirationDate: '2025/01',
				},
			},
			{
				headers: {
					'Access-Control-Allow-Origin': '*',
					'Content-Type': 'application/json',
					Accept: 'application/json',
				},
			}
		);
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<button onClick={handleTokenizeCard}>Crear tarjeta con PayU</button>
			</div>
		</>
	);
}
